issuer: {{ .Env.OIDC_ISSUER }}

storage:
  type: memory

web:
  http: 0.0.0.0:5556
  allowedOrigins: ["*"]

logger:
  level: debug
  format: text

enablePasswordDB: true

staticClients:
  - id: excalidraw
    redirectURIs:
      - {{ .Env.OIDC_REDIRECT_URL }}
    name: Excalidraw
    public: true
    secret: {{ .Env.OIDC_CLIENT_SECRET }}

staticPasswords:
  - email: {{ .Env.ADMIN_EMAIL }}
    hash: {{ .Env.ADMIN_PASSWORD_HASH }}
    username: {{ .Env.ADMIN_USERNAME }}
    userID: {{ .Env.ADMIN_USER_ID }}
