name = "excalidraw-worker"
main = "index.js"
compatibility_date = "2023-08-01"

[durable_objects]
bindings = [
  { name = "CANVAS_OBJECT", class_name = "CanvasObject" },
  { name = "INDEX_OBJECT", class_name = "IndexObject" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CanvasObject", "IndexObject"] 