linters-settings:
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    enable:
      - shadow
  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - goconst
    - gocritic
    - misspell
    - unparam

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - errcheck

run:
  timeout: 5m
  skip-dirs:
    - vendor
    - target
