version: 2

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goconst
    - gocritic
    - misspell
    - unparam
  settings:
    errcheck:
      check-type-assertions: true
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    govet:
      enable:
        - shadow
  exclusions:
    paths:
      - vendor
      - target
    rules:
      - path: _test\.go
        linters:
          - goconst
          - errcheck

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m
